### ISSUE TITLE
🐛[BUG]: Undefined environment variables -- distributed manager

### ISSUE THREAD

**Issue by lucapegolotti** [NVIDIA/modulus#158]
### Version

Main branch - commit 2d8e08c

### On which installation method(s) does this occur?

`pip install .` launched from the root of the project in a virtual environment.

### Describe the issue

While trying to instantiate a DistributedManager on a slurm-based system, I get the following error:

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/scratch/users/lpego/modulus-venv/lib/python3.8/site-packages/modulus/distributed/manager.py", line 290, in initialize
    DistributedManager.initialize_env()
  File "/scratch/users/lpego/modulus-venv/lib/python3.8/site-packages/modulus/distributed/manager.py", line 205, in initialize_env
    rank = int(os.environ.get("RANK"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 244, in do_training
    DistributedManager.initialize()
  File "/scratch/users/lpego/modulus-venv/lib/python3.8/site-packages/modulus/distributed/manager.py", line 293, in initialize
    DistributedManager.initialize_slurm(port)
  File "/scratch/users/lpego/modulus-venv/lib/python3.8/site-packages/modulus/distributed/manager.py", line 245, in initialize_slurm
    world_size = int(os.environ.get("SLURM_NPROCS"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
This can be solved by setting `export RANK=0` leading to similar issue that can be solved (in my case) with  `export WORLD_SIZE=1`, `export MASTER_ADDR=127.0.0.1`.

**Comment by NickGeneva** [comment]
Seems to of been an issue with the SLURM environment not having different environment variables set. These can vary from machine to machine depending on what the sys admins decide.

For those that may encounter similar issues modulus looks at the following Slurm variables:
https://github.com/NVIDIA/modulus/blob/main/modulus/distributed/manager.py#L247

Closing for now since system specific, but thank you for the report for other users.
