### ISSUE TITLE
🐛[BUG]: import modulus throws error: `No module named 'importlib_metadata'`

### ISSUE THREAD

**Issue by Saydemr** [NVIDIA/modulus#336]
### Version

0.5.0

### On which installation method(s) does this occur?

Pip

### Describe the issue

Upon installing modulus with pip, importing the library throws import error because `importlib_metadata` is not included in the dependency tree of the repository. 

Import error is thrown due to [this line](https://github.com/NVIDIA/modulus/blob/6b22b58bafd623d01bc3df6d05bf81e105b7b11c/modulus/registry/model_registry.py#L21) in the code.

### Minimum reproducible example

```shell
pip install nvidia-modulus
python
>>> import modulus
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<username>/anaconda3/envs/mod/lib/python3.10/site-packages/modulus/__init__.py", line 17, in <module>
    from .models.meta import ModelMetaData
  File "/home/<username>/anaconda3/envs/mod/lib/python3.10/site-packages/modulus/models/__init__.py", line 15, in <module>
    from .module import Module
  File "/home/<username>/anaconda3/envs/mod/lib/python3.10/site-packages/modulus/models/module.py", line 29, in <module>
    from modulus.registry import ModelRegistry
  File "/home/<username>/anaconda3/envs/mod/lib/python3.10/site-packages/modulus/registry/__init__.py", line 15, in <module>
    from .model_registry import ModelRegistry
  File "/home/<username>/anaconda3/envs/mod/lib/python3.10/site-packages/modulus/registry/model_registry.py", line 19, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

### Environment details

```shell
+ Environment location: Bare-metal
+ Python : 3.10.13
+ pip : 23.3.1
```

**Comment by N-Masi** [comment]
For anyone else facing this issue, if it's not obvious, the solution is to run `pip install importlib-metadata` in your environment. Another dependency that is not installed in the same overlooked way is the `requests` module.

**Comment by ktangsali** [comment]
This should be fixed in the latest release. Please try again and re-open if the issue persists.
