### ISSUE TITLE
🐛[BUG]: CorrDiff: improper default value for `max_norm`

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#460]
### Version

Latest

### Describe the issue

Traceback (most recent call last):
  File "/code/mnabian/PRs/out/modulus/examples/generative/corrdiff/train.py", line 341, in main
    training_loop.training_loop(
  File "/code/mnabian/PRs/out/modulus/examples/generative/corrdiff/training/training_loop.py", line 294, in training_loop
    grad_norm = torch.nn.utils.clip_grad_norm_(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/clip_grad.py", line 40, in clip_grad_norm_
    max_norm = float(max_norm)
ValueError: could not convert string to float: 'None'

**Comment by mnabian** [comment]
@tge25 could you please fix this?
