### ISSUE TITLE
🐛[BUG]: Instantiating `EDMPrecondSR` fails from `TypeError: got an unexpected keyword argument 'scale_cond_input'` with `modulus==0.8.0` (Modulus container 24.09)

### ISSUE THREAD

**Issue by luke-conibear** [NVIDIA/modulus#694]
### Version

0.8.0

### On which installation method(s) does this occur?

Docker

### Describe the issue

Instantiating `EDMPrecondSR` fails from `TypeError: got an unexpected keyword argument 'scale_cond_input'` with `modulus==0.8.0` (Modulus container 24.09)

- Copying [unit test example](https://github.com/NVIDIA/modulus/blob/main/test/models/diffusion/test_preconditioning.py#L61): `EDMPrecondSR(8, 1, 1, 1, scale_cond_input=False)`
- Workaround by installing the repository directly instead of `0.8.0`: `pip install --force-reinstall git+https://github.com/NVIDIA/modulus.git`

### Minimum reproducible example

```bash
$ docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 --rm -it nvcr.io/nvidia/modulus/modulus:24.09 bash

====================
== NVIDIA Modulus ==
====================

NVIDIA Release 24.09 (build 18526012)
Modulus PyPi Version 0.8.0 (Git Commit: eb01d2a)
Modulus Sym PyPi Version 1.7.0 (Git Commit: 249b76a)
Container image Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Copyright (c) 2014-2024 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

root@68fd1b511c77:/workspace# python
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from modulus.models.diffusion import EDMPrecondSR
>>> EDMPrecondSR(8, 1, 1, 1, scale_cond_input=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/modulus/models/diffusion/preconditioning.py", line 752, in __init__
    self.model = model_class(
  File "/usr/local/lib/python3.10/dist-packages/modulus/models/module.py", line 65, in __new__
    bound_args = sig.bind_partial(
  File "/usr/lib/python3.10/inspect.py", line 3193, in bind_partial
    return self._bind(args, kwargs, partial=True)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'scale_cond_input'
>>> exit()
root@68fd1b511c77:/workspace# pip install --force-reinstall git+https://github.com/NVIDIA/modulus.git
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/NVIDIA/modulus.git
...
root@68fd1b511c77:/workspace# python
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from modulus.models.diffusion import EDMPrecondSR
Error in cpuinfo: prctl(PR_SVE_GET_VL) failed
>>> EDMPrecondSR(8, 1, 1, 1, scale_cond_input=False)
EDMPrecondSR(
  (model): SongUNetPosEmbd(
    (map_noise): PositionalEmbedding()
    (map_layer0): Linear()
    (map_layer1): Linear()
    (enc): ModuleDict(
      ...
```

### Relevant log output

See above

### Environment details

See above

**Comment by luke-conibear** [comment]
This is fixed with `modulus==0.9.0` using `nvcr.io/nvidia/modulus/modulus:24.12`
