### ISSUE TITLE
🐛[BUG]: FigConvNet Reproduce

### ISSUE THREAD

**Issue by wangguan1995** [NVIDIA/modulus#705]
### Version

develop

### Describe the issue

Follow instruction from "https://github.com/NVIDIA/modulus/pull/679/files#diff-d700b7bbccb92ea79aa4e573f332abd1e4f3369ee81726db435f48f7a41c017f"

Trying to Reproduce

```
python train.py \
    +experiment=drivaernet/figconv_unet \
    data.data_path=./datasets/drivaer/
```
2024-11-04 06:41:57,857 - SignalHandler - ERROR - Exception: <class 'hydra.errors.InstantiationException'> - Error locating target 'src.data.DrivAerNetDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
2024-11-04 06:41:57,857 - SignalHandler - DEBUG - Writing status: ERROR to file: /workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/outputs/2024-11-04/06-41-51/status.txt
Error executing job with overrides: ['+experiment=drivaernet/figconv_unet', 'data.data_path=/workspace/gino_data/6_DrivAir_p/']
Traceback (most recent call last):
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src' has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/root/miniconda3/envs/dfc/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/src/data/__init__.py", line 17, in <module>
    from .base_datamodule import BaseDataModule
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/src/data/base_datamodule.py", line 17, in <module>
    import webdataset as wds
ModuleNotFoundError: No module named 'webdataset'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.data.DrivAerNetDataModule':
ModuleNotFoundError("No module named 'webdataset'")
Are you sure that 'data' is importable from module 'src'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/train.py", line 450, in <module>
    main()
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/train.py", line 433, in main
    train(config, signal_handler)
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/train.py", line 229, in train
    datamodule = instantiate(config.data)
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.data.DrivAerNetDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
Traceback (most recent call last):
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src' has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/root/miniconda3/envs/dfc/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/src/data/__init__.py", line 17, in <module>
    from .base_datamodule import BaseDataModule
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/src/data/base_datamodule.py", line 17, in <module>
    import webdataset as wds
ModuleNotFoundError: No module named 'webdataset'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.data.DrivAerNetDataModule':
ModuleNotFoundError("No module named 'webdataset'")
Are you sure that 'data' is importable from module 'src'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/train.py", line 450, in <module>
    main()
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/train.py", line 433, in main
    train(config, signal_handler)
  File "/workspace/DNNFluid_Car/modulus/examples/cfd/figconvnet/train.py", line 229, in train
    datamodule = instantiate(config.data)
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/miniconda3/envs/dfc/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.data.DrivAerNetDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
```

### Minimum reproducible example

_No response_

### Relevant log output

_No response_

### Environment details

_No response_

**Comment by wangguan1995** [comment]
@Alexey-Kamenev
